const $=id=>document.getElementById(id);let pc,dc,mic,cam,audio,interval,renew,started=0,faceBusy=false,connecting=false,epoch=0;
function status(s){$('status').textContent=s}function log(s){$('transcript').textContent=($('transcript').textContent+'\n'+s).slice(-16000)}
function bind(id,fn){$(id).onclick=async()=>{try{await fn()}catch(e){status(e.message)}}}
async function refresh(){const ps=await ava.profiles();$('profiles').replaceChildren(...ps.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;return o}))}
function event(e){if(dc?.readyState==='open')dc.send(JSON.stringify(e));else throw Error('Session déconnectée')}
function image(){if(!cam||!$('camera').videoWidth)throw Error('Activer la caméra');const c=document.createElement('canvas');c.width=640;c.height=480;c.getContext('2d').drawImage($('camera'),0,0,640,480);return c.toDataURL('image/jpeg',.7)}
async function captureVoice(){const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});const ctx=new AudioContext({sampleRate:16000});await ctx.resume();const src=ctx.createMediaStreamSource(stream),proc=ctx.createScriptProcessor(4096,1,1),mute=ctx.createGain();mute.gain.value=0;const chunks=[];proc.onaudioprocess=e=>chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)));src.connect(proc);proc.connect(mute);mute.connect(ctx.destination);try{await new Promise(r=>setTimeout(r,5000));const length=chunks.reduce((s,c)=>s+c.length,0),a=new Float32Array(length);let n=0;for(const c of chunks){a.set(c,n);n+=c.length}const bytes=new Uint8Array(a.buffer);let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));return {audio:btoa(str),rate:ctx.sampleRate}}finally{proc.disconnect();src.disconnect();stream.getTracks().forEach(t=>t.stop());await ctx.close()}}
function stop(){epoch++;clearInterval(interval);clearTimeout(renew);dc?.close();pc?.close();mic?.getTracks().forEach(t=>t.stop());if(audio){audio.pause();audio.srcObject=null}pc=dc=mic=null;status('Session arrêtée · micro coupé');$('timer').textContent='Micro coupé'+(cam?' · caméra active':' · caméra coupée')}
async function start(){if(connecting||pc)throw Error('Session déjà active');if(!$('consent').checked)throw Error('Accepter l’écoute avant de démarrer');connecting=true;const token=++epoch;try{if($('lock').checked){const f=await ava.bio('verify_face',{image:image()});if(!f.match)throw Error('Visage non reconnu');status('Dis ton nom et quelques mots pendant 5 secondes');const v=await ava.bio('verify_voice',await captureVoice());if(!v.match)throw Error('Voix non reconnue')}if(token!==epoch)return;mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(token!==epoch){mic.getTracks().forEach(t=>t.stop());return}pc=new RTCPeerConnection();audio=new Audio();audio.autoplay=true;pc.ontrack=e=>{audio.srcObject=e.streams[0];audio.play().catch(()=>status('Lecture audio bloquée'))};pc.onconnectionstatechange=()=>{if(pc&&['failed','disconnected','closed'].includes(pc.connectionState))stop()};mic.getTracks().forEach(t=>pc.addTrack(t,mic));dc=pc.createDataChannel('oai-events');dc.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='error')status(data.error?.message||'Erreur API');if(data.type==='response.output_audio_transcript.done')log('AVA : '+data.transcript);if(data.type==='input_audio_buffer.speech_started')status('Je t’écoute…');if(data.type==='response.done')status('AVA connectée')};const offer=await pc.createOffer();await pc.setLocalDescription(offer);const answer=await ava.connect(offer.sdp,$('voice').value);if(token!==epoch)return;await pc.setRemoteDescription({type:'answer',sdp:answer});started=Date.now();status('AVA connectée · micro actif');let ticks=0;interval=setInterval(async()=>{if(token!==epoch)return;$('timer').textContent=`Micro actif · ${Math.floor((Date.now()-started)/1000)} s · caméra ${cam?'active':'coupée'}`;ticks++;if($('lock').checked&&!faceBusy){faceBusy=true;try{const f=await ava.bio('verify_face',{image:image()});if(token===epoch&&!f.match){stop();status('Visage absent ou non reconnu : session coupée')}}catch(e){if(token===epoch){stop();status(e.message)}}finally{faceBusy=false}}if(ticks%5===0&&$('vision').checked&&cam&&token===epoch){try{event({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_image',image_url:image()}]}})}catch(e){status(e.message)}}},3000);renew=setTimeout(()=>{stop();status('Limite locale de 20 minutes atteinte. Relance la session si souhaité.')},20*60*1000)}catch(e){if(token===epoch)stop();throw e}finally{connecting=false}}
bind('create',async()=>{await ava.create($('name').value,$('pin').value);await refresh();status('Profil créé. Ouvre-le avec ton code.')});
bind('enter',async()=>{const p=await ava.login($('profiles').value,$('pin').value);$('pin').value='';$('login').hidden=true;$('workspace').hidden=false;$('greeting').textContent='Bonjour '+p.name;$('memory').value=p.memory.join('\n');$('apiKey').value='';status(p.hasKey?'Clé disponible sur ce PC':'Ajoute ta clé API personnelle')});
bind('saveKey',async()=>{await ava.key($('apiKey').value);$('apiKey').value='';status('Clé enregistrée')});
bind('cam',async()=>{if(cam){if($('lock').checked)stop();cam.getTracks().forEach(t=>t.stop());cam=null;$('camera').srcObject=null}else{cam=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480},audio:false});$('camera').srcObject=cam}status(cam?'Caméra active : aperçu local':'Caméra coupée')});
bind('faceEnroll',async()=>{status('Enregistrement du visage…');const r=await ava.bio('enroll_face',{image:image()});status(r.message)});
bind('voiceEnroll',async()=>{stop();status('Parle naturellement pendant 5 secondes');const r=await ava.bio('enroll_voice',await captureVoice());status(r.message)});
bind('start',start);bind('stop',stop);
bind('send',()=>{const text=$('text').value.trim();if(!text)return;event({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text}]}});event({type:'response.create'});log('Toi : '+text);$('text').value=''});
bind('saveMemory',async()=>{await ava.memory($('memory').value.split('\n').map(x=>x.trim()).filter(Boolean));status('Souvenirs enregistrés pour la prochaine session')});
bind('forget',async()=>{await ava.memory([]);$('memory').value='';stop();$('transcript').textContent='';status('Souvenirs effacés')});
async function leave(){stop();cam?.getTracks().forEach(t=>t.stop());cam=null;$('camera').srcObject=null;await ava.logout();$('workspace').hidden=true;$('login').hidden=false;$('transcript').textContent='';$('memory').value='';await refresh()}
bind('leave',leave);bind('remove',async()=>{if(confirm('Supprimer définitivement ce profil, sa clé, ses souvenirs et ses empreintes ?')){stop();await ava.delete();await leave()}});window.addEventListener('beforeunload',stop);refresh().catch(e=>status(e.message));
